require: rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
