require: rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 180

RSpec/ExampleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/MutableConstant:
  Enabled: false
