# frozen_string_literal: true

source 'https://rubygems.org'

gem 'reek'
gem 'rspec'
gem 'simplecov'

gem 'rubocop'
gem 'rubocop-rspec'

gem 'guard'
gem 'guard-rspec'
gem 'guard-rubocop'

gem 'matrix'
gem 'geom2d'
gem 'geometry-in-ruby'
