# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sorbet'
gem 'sorbet-runtime'
gem 'tapioca', '~> 0.17', require: false

gem 'reek'
gem 'rspec'
gem 'simplecov'

gem 'rubocop'
gem 'rubocop-rspec'

gem 'guard'
gem 'guard-rspec'
gem 'guard-rubocop'

gem 'chunky_png'
gem 'matrix'
gem 'rb_heap'
